-- Use DB
USE floris;

-- Baby
CREATE TABLE IF NOT EXISTS Baby (ID VARCHAR(20) PRIMARY KEY  NOT NULL  UNIQUE , Timestamp TIMESTAMP DEFAULT 0 ,  Name VARCHAR(20) NOT NULL UNIQUE , DOB DATE , DueDay DATE , Gender TINYINT , Picture VARCHAR(255));
CREATE INDEX BabyIndexName ON Baby (Name ASC);

