-- Use DB
USE floris;

-- Baby
#INSERT INTO Baby (ID VARCHAR(20) PRIMARY KEY  NOT NULL  UNIQUE , Timestamp TIMESTAMP DEFAULT 0 ,  Name VARCHAR(20) NOT NULL UNIQUE , DOB DATE , DueDay DATE , Gender TINYINT , Picture VARCHAR(255));
INSERT INTO Baby VALUES ("BabyID1" , TIMESTAMP(CURDATE()),  "BabyName1" , CURDATE(), CURDATE()+10, 1 , "BabyPic1");
