<?php
 
/*
 * Error Code
 */

define('ERROR_CODE_SUCCESS', 0);
define('ERROR_CODE_USER_CREATED_SUCCESSFULLY', 1);
define('ERROR_CODE_USER_CREATE_FAILED', 2);
define('ERROR_CODE_USER_ALREADY_EXISTED', 3);

define('ERROR_CODE_LOGIN_FAILED', 4);
define('ERROR_CODE_LOGIN_WRONG_CREDENTIAL', 5);


?>
